"""Primeira versão do banco

Revision ID: 3ddbcc3c5527
Revises: 
Create Date: 2024-07-09 09:25:22.434353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddbcc3c5527'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'funcionario', ['cpf'])
    op.create_unique_constraint(None, 'registroBanco', ['cod_banco'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registroBanco', type_='unique')
    op.drop_constraint(None, 'funcionario', type_='unique')
    # ### end Alembic commands ###
