"""teste 1

Revision ID: 755c826c5004
Revises: 
Create Date: 2024-06-27 10:22:40.334713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755c826c5004'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('cod_estado', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('cod_estado')
    )
    op.create_table('registroBanco',
    sa.Column('cod_banco', sa.String(length=10), nullable=False),
    sa.Column('nome_banco', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cod_banco'),
    sa.UniqueConstraint('cod_banco')
    )
    op.create_table('cidade',
    sa.Column('cod_municipio', sa.String(length=250), nullable=False),
    sa.Column('cod_estado', sa.Integer(), nullable=False),
    sa.Column('habitantes', sa.Integer(), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['cod_estado'], ['estado.cod_estado'], name='fk_cod_estado'),
    sa.PrimaryKeyConstraint('cod_municipio')
    )
    op.create_table('funcionario',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=True),
    sa.Column('endereco', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('data_nasc', sa.Date(), nullable=True),
    sa.Column('rg', sa.String(length=12), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('cod_banco', sa.String(length=10), nullable=True),
    sa.Column('agencia', sa.String(length=10), nullable=True),
    sa.Column('conta_corrente', sa.String(length=10), nullable=True),
    sa.Column('matricula', sa.String(length=10), nullable=True),
    sa.Column('posto_trabalho', sa.String(length=10), nullable=True),
    sa.Column('cargo', sa.String(length=10), nullable=True),
    sa.Column('cidade', sa.String(length=10), nullable=True),
    sa.Column('centro_custo', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['cod_banco'], ['registroBanco.cod_banco'], name='fk_cod_banco'),
    sa.PrimaryKeyConstraint('cpf'),
    sa.UniqueConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionario')
    op.drop_table('cidade')
    op.drop_table('registroBanco')
    op.drop_table('estado')
    # ### end Alembic commands ###
