"""V2 banco de dados

Revision ID: f305d56b5a29
Revises: 
Create Date: 2024-07-17 14:36:44.515293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f305d56b5a29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('cod_estado', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('cod_estado')
    )
    op.create_table('funcionario',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=True),
    sa.Column('endereco', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.String(length=250), nullable=True),
    sa.Column('data_nasc', sa.Date(), nullable=True),
    sa.Column('rg', sa.String(length=12), nullable=True),
    sa.Column('telefone', sa.String(length=13), nullable=True),
    sa.Column('cod_banco', sa.String(length=4), nullable=True),
    sa.Column('nome_banco', sa.String(length=150), nullable=True),
    sa.Column('agencia', sa.String(length=6), nullable=True),
    sa.Column('conta_corrente', sa.String(length=14), nullable=True),
    sa.Column('matricula', sa.String(length=20), nullable=True),
    sa.Column('posto_trabalho', sa.String(length=250), nullable=True),
    sa.Column('cargo', sa.String(length=150), nullable=True),
    sa.Column('cidade', sa.String(length=250), nullable=True),
    sa.Column('centro_custo', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('cpf'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('numero_sd',
    sa.Column('ultimo_numero', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ultimo_numero')
    )
    op.create_table('cidade',
    sa.Column('cod_municipio', sa.Integer(), nullable=False),
    sa.Column('cod_estado', sa.Integer(), nullable=False),
    sa.Column('habitantes', sa.Integer(), nullable=False),
    sa.Column('cidade', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['cod_estado'], ['estado.cod_estado'], name='fk_cod_estado'),
    sa.PrimaryKeyConstraint('cod_municipio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cidade')
    op.drop_table('numero_sd')
    op.drop_table('funcionario')
    op.drop_table('estado')
    # ### end Alembic commands ###
